
import { MarketInsight } from "./types";

export const generateMockInsights = (count: number = 6): MarketInsight[] => {
  const insights: MarketInsight[] = [
    {
      id: "1",
      title: "Bitcoin Rally Continues",
      description: "Institutional adoption driving cryptocurrency prices to new heights with strong momentum expected.",
      industryType: "financial",
      industryLabel: "Financial Markets",
      marketValue: 42750.50,
      changePercentage: 8.5,
      changeDirection: "up",
      confidence: 0.78,
      timeframe: "24h",
      source: "Market Analysis",
      tags: ["crypto", "institutional", "rally"],
      insights: ["Strong institutional buying", "Technical breakout pattern", "Increased trading volume"],
      predictedChange: 12.3,
      timestamp: new Date().toISOString(),
      sparklineData: [100, 105, 110, 115, 108, 112, 118]
    },
    {
      id: "2", 
      title: "Housing Market Resilience",
      description: "Regional markets showing unexpected strength despite rising interest rates and economic uncertainty.",
      industryType: "housing",
      industryLabel: "Real Estate",
      marketValue: 485000,
      changePercentage: 15.2,
      changeDirection: "up", 
      confidence: 0.76,
      timeframe: "Monthly",
      source: "Real Estate Analytics",
      tags: ["housing", "regional", "growth"],
      insights: ["Supply constraints persist", "Tech migration continues", "Low inventory levels"],
      predictedChange: 18.7,
      timestamp: new Date(Date.now() - 3600000).toISOString(),
      sparklineData: [95, 98, 102, 108, 112, 115, 118]
    },
    {
      id: "3",
      title: "Green Hydrogen Breakthrough", 
      description: "Record investment in hydrogen infrastructure signals major shift toward clean energy solutions.",
      industryType: "green_hydrogen",
      industryLabel: "Green Energy",
      marketValue: 450000000,
      changePercentage: 28.5,
      changeDirection: "up",
      confidence: 0.85,
      timeframe: "Quarterly", 
      source: "Energy Transition Report",
      tags: ["hydrogen", "clean energy", "investment"],
      insights: ["European mandates accelerating adoption", "Technology costs declining", "Industrial demand growing"],
      predictedChange: 35.2,
      timestamp: new Date(Date.now() - 7200000).toISOString(),
      sparklineData: [80, 85, 92, 98, 105, 112, 125]
    },
    {
      id: "4",
      title: "Copper Supply Constraints",
      description: "Mining disruptions and renewable energy demand creating significant market opportunities.",
      industryType: "mining", 
      industryLabel: "Mining & Commodities",
      marketValue: 4250000000,
      changePercentage: 15.8,
      changeDirection: "up",
      confidence: 0.77,
      timeframe: "Weekly",
      source: "Commodities Insight", 
      tags: ["copper", "supply", "renewable"],
      insights: ["Green energy transition driving demand", "Supply disruptions in major mines", "Infrastructure spending increasing"],
      predictedChange: 22.1,
      timestamp: new Date(Date.now() - 10800000).toISOString(),
      sparklineData: [320, 325, 335, 345, 355, 365, 380]
    },
    {
      id: "5",
      title: "Agricultural Technology Surge",
      description: "Precision farming and climate adaptation technologies attracting unprecedented investment.",
      industryType: "agriculture",
      industryLabel: "Agriculture & Food",
      marketValue: 8750000,
      changePercentage: 25.6,
      changeDirection: "up", 
      confidence: 0.81,
      timeframe: "Annual",
      source: "AgTech Today",
      tags: ["agtech", "precision farming", "climate"],
      insights: ["Climate-resistant crops in demand", "IoT adoption accelerating", "Sustainability focus driving investment"],
      predictedChange: 30.4,
      timestamp: new Date(Date.now() - 14400000).toISOString(),
      sparklineData: [180, 185, 195, 210, 225, 245, 265]
    },
    {
      id: "6",
      title: "Telemedicine Expansion",
      description: "Healthcare technology platforms expanding rapidly into underserved rural markets globally.",
      industryType: "medical",
      industryLabel: "Healthcare Tech", 
      marketValue: 4200000,
      changePercentage: 38.5,
      changeDirection: "up",
      confidence: 0.68,
      timeframe: "Quarterly",
      source: "HealthTech Analytics",
      tags: ["telemedicine", "rural health", "expansion"],
      insights: ["Rural healthcare access improving", "Regulatory barriers reducing", "Insurance coverage expanding"],
      predictedChange: 42.8,
      timestamp: new Date(Date.now() - 18000000).toISOString(),
      sparklineData: [65, 70, 78, 88, 98, 110, 125]
    }
  ];

  return insights.slice(0, count);
};
