// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlqnfmhekpnewbueodum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5scW5mbWhla3BuZXdidWVvZHVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3NzcwNDMsImV4cCI6MjA1NDM1MzA0M30.6OqipAtA8GiuVpTY-eBcF9o8M8RUi9Ul6kXJKFgKsmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);